name: BSP Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy as BSP application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: yarn
      - name: Build and deploy BSP application
        run: yarn deploy-bsp
        env:
          UI5_TASK_NWABAP_DEPLOYER__SERVER: ${{ secrets.UI5_TASK_NWABAP_DEPLOYER__SERVER }}
          UI5_TASK_NWABAP_DEPLOYER__USER: ${{ secrets.UI5_TASK_NWABAP_DEPLOYER__USER }}
          UI5_TASK_NWABAP_DEPLOYER__PASSWORD: ${{ secrets.UI5_TASK_NWABAP_DEPLOYER__PASSWORD }}
          UI5_TASK_NWABAP_DEPLOYER__TRANSPORTNO: ${{ secrets.UI5_TASK_NWABAP_DEPLOYER__TRANSPORTNO }}
          UI5_TASK_NWABAP_DEPLOYER__CLIENT: ${{ secrets.UI5_TASK_NWABAP_DEPLOYER__CLIENT }}
